[package]
name = "dyno_types"
version = "0.1.0"
authors = ["Rizal Achmad Pahlevi <rizal.ahmadp@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/RizalAchp/dynotest-rs/"
# license = "MIT"
# license-file = "LICENSE"
keywords = ["network", "graphics", "embeded", "gui", "client", "math", "server"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default     = ["use_log", "use_serde", "use_chrono", "use_excel", "bigger_float"]

backend         = ["dep:actix-web"]
frontend        = ["dep:reqwest"]
use_log         = ["dep:log"]
use_excel       = ["dep:calamine", "dep:rust_xlsxwriter"]
use_regex       = ["dep:regex"]
use_chrono      = ["dep:chrono"]
use_serde       = ["dep:serde", "dep:bincode", "dep:derive_more", "dep:serde_json", "dep:toml"]
bigger_float    = []

[dependencies]
chrono      = { optional = true, version = "0.4", features = ["serde"]}
toml        = { optional = true, version = "0.7" }
bincode     = { optional = true, version = "1" }
serde_json  = { optional = true, version = "1" }
derive_more = { optional = true, version = "0.99" }
serde       = { optional = true, version = "1", features = ["derive"] }

log         = { optional = true, version = "0.4" }
regex       = { optional = true, version = "1.7" } # For checking if we need to skip auth

reqwest     = { optional = true, version = "0.11.14", features = ["json", "blocking", "rustls"], default-features = false }

# umya-spreadsheet = { optional = true, version = "0.9.0" }
calamine            = { optional = true, version = "0.19", features = ["dates"] }
rust_xlsxwriter     = { optional = true, version = "0.32" }
paste = "1.0.12"
lazy_static = "1.4.0"

[dependencies.actix-web]
version = "4"
optional = true
default-features = false
